#ifndef CSAFEMEMZ_EVENT_H
#define CSAFEMEMZ_EVENT_H

typedef enum
{
    EVENT_NONE = 0,
    EVENT_GLITCH,
    EVENT_SHAKE,
    EVENT_TEAR,
    EVENT_COLOR_SHIFT,
    EVENT_RECTS,
    EVENT_FLASH,
    EVENT_SWIRL,
    EVENT_SCANLINES,
    EVENT_PIXELATE,
    EVENT_MIRROR,
    EVENT_RGB_SPLIT,
    EVENT_WAVE,
    EVENT_INVERT,
    EVENT_VERTICAL_TEAR,
    EVENT_BARS,
    EVENT_CHECKER,
    EVENT_ZOOM,
    EVENT_NOISE,
    EVENT_WARP,
    EVENT_COLOR_BANDS,
    EVENT_SPIRAL,
    EVENT_FAKE_NOTEPAD,
    EVENT_FAKE_BROWSER,
    EVENT_FAKE_ERROR,
    EVENT_FAKE_CMD,
    EVENT_FAKE_EXPLORER,
    EVENT_FAKE_CRASH,
    EVENT_DESKTOP_FLICKER,
    EVENT_CHAOS,
    EVENT_FINAL
} EventType;

void EventStart(EventType event);
void EventStop(EventType event);

#endif
